---
version: '3'
services:
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: grafana
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:3000:3000"

